Repository phovea/phovea_processing_queue, pull requests merged in 2020-03, with the labels that each got.

#32 Update to Typescript 3.8
  package.json
  tsconfig.json
Labels: priority: high, release: major, type: refactor

#37 Update dependencies and requirements
  package.json
  requirements_dev.txt
Labels: priority: medium, type: refactor

#39 Change `buildId` to `JSON.stringify(buildId)`
  webpack.config.js
Labels: priority: medium, type: refactor

#40 Release 4.0.0
  .github/CODEOWNERS
  package.json
  requirements.txt
  requirements_dev.txt
  tsconfig.json
  webpack.config.js
Labels: release: major

#30 Migrate to jest for testing
  jest.config.js
  karma.conf.js
  package.json
  tsd.d.ts
Labels: release: major, type: refactor

#43 Enable gif and webp files
  tsd.d.ts
Labels: type: refactor
